from tkinter import *
from dbconnect import *
from tkinter.messagebox import showinfo
def prop():
    def getinfo():
        a=int(pid.get())
        b=title.get()
        c=int(price.get())
        d=add.get()
        e=int(rid.get())
        f=date.get()
        g=ptype.get()
        h=extras.get()
        i=int(bed.get())
        j=int(wash.get())
        k=int(park.get())
        query=f"insert into properties(propertyid,title,price,address,realtor_id,listingdate,type,amenities,bedrooms,washrooms,parking)  values('{a}','{b}','{c}','{d}','{e}','{f}','{g}','{h}',{i},{j},{k})"
        alterations(query)
        showinfo(title='Insertion',message='Inserted Success')
        pid.delete(0,END)
        title.delete(0,END)
        price.delete(0,END)
        add.delete(0,END)
        rid.delete(0,END)
        date.delete(0,END)
        ptype.delete(0,END)
        extras.delete(0,END)
        bed.delete(0,END)
        wash.delete(0,END)
        park.delete(0,END)



    root=Tk()
    root.title(" Property details")
    root.geometry("500x500")


    frame1=Frame(root,padx=5,pady=5)
    frame1.grid(row=1,column=1)
    Label(root,text="Property DETAILS",padx=5).grid(row=0,columnspan=5,pady=7)
    l1=Label(frame1,text="Property ID",padx=30,pady=10).pack()
    l2=Label(frame1,text="Title",padx=30,pady=5).pack()
    l3=Label(frame1,text="Price",padx=30,pady=5).pack()
    l4=Label(frame1,text="Address",padx=30,pady=5).pack()
    l5=Label(frame1,text="Realtor id",padx=30,pady=5).pack()
    l6=Label(frame1,text="Listing Date",padx=30,pady=5).pack()
    l7=Label(frame1,text="Type",padx=30,pady=5).pack()
    l8=Label(frame1,text="Amenities",padx=30,pady=5).pack()
    l9=Label(frame1,text="Bedrooms",padx=30,pady=5).pack() 
    l10=Label(frame1,text="Washrooms",padx=30,pady=5).pack()    
    l11=Label(frame1,text="parking",padx=30,pady=5).pack()               

    frame2=Frame(root,padx=5,pady=5)
    frame2.grid(row=1,column=2)
    pid=Entry(frame2)
    pid.pack(padx=5,pady=5)
    title=Entry(frame2)
    title.pack(padx=5,pady=5)
    price=Entry(frame2)
    price.pack(padx=5,pady=5)
    add=Entry(frame2)
    add.pack(padx=5,pady=5)
    rid=Entry(frame2)
    rid.pack(padx=5,pady=5)
    date=Entry(frame2)
    date.pack(padx=5,pady=5)
    ptype=Entry(frame2)
    ptype.pack(padx=5,pady=5)
    extras=Entry(frame2)
    extras.pack(padx=5,pady=5)
    bed=Entry(frame2)
    bed.pack(padx=5,pady=5)
    wash=Entry(frame2)
    wash.pack(padx=5,pady=5)
    park=Entry(frame2)
    park.pack(padx=5,pady=5)
    Button(root,text="Submit",command=getinfo).grid(row=2,columnspan=5,pady=5)
    root.mainloop()
